chore: use pep8 for styling
Arrow-air/tools pull request #25
Opened 2023-03-12 18:06 UTC by GoodluckH

2023-03-13 15:04 UTC, owlot requested changes
You also need to bump the version in the .env file so a new image will be built.
Otherwise the publish workflow will not run

2023-03-13 19:03 UTC, GoodluckH commented
> You also need to bump the version in the .env file so a new image will be built. Otherwise the publish workflow will not run

[25f791e](https://github.com/Arrow-air/tools/pull/25/commits/25f791e00bb22c238cb663c1c42ddf32f59f0124)

2023-03-14 00:29 UTC, ServiceDog approved these changes, later dismissed

2023-03-14 08:34 UTC, owlot submitted a review, later dismissed

2023-03-15 12:10 UTC, owlot approved these changes

2023-03-15 12:10 UTC, merged